application:
  name: next.js
  project: clovis
  organization: QoveryCommunity
databases:
- type: postgresql
  version: "12"
  name: my-postgresql-database
routers:
- name: main
  routes:
  - application_name: next.js
    paths:
    - /*
