application:
  name: hasura
  project: clovis
  organization: QoveryCommunity
databases:
- type: postgresql
  version: "12"
  name: clovis
routers:
- name: main
  routes:
  - application_name: hasura
    paths:
    - /api/hasura/
